Models/Siniflar/Marka.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace mvc_net_Crm.Models.Siniflar
{
    public class Marka
    {
        public Marka() //DEFAULT BILGILER VERILIYOR
        {
            Durum = true;
        }

        [Key]
        public int MarkaID { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string MarkaAd { get; set; }
        public bool Durum { get; set; }
        public ICollection<Urun> Uruns { get; set; }//Marka 1- % Urun
        }

}

Controllers/MarkaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvc_net_Crm.Models.Siniflar;

namespace mvc_net_Crm.Controllers
{
    public class MarkaController : Controller
    {
        Context c = new Context();
        // GET: Marka
        public ActionResult Index()
        {
            //var departmanlar=c.Departmans.ToList();//KOSULSUZ LISTELEME
            var markalar = c.Markas.Where(x => x.Durum == true).ToList();//KOSULLU LISTELEME
            return View(markalar);
        }
        [HttpGet]
        public ActionResult MarkaEkle() //BOS FORM SAYFASI CAGIRIYOR
        {
            //DROPDOWN DB LISTESINDEN VERI CEKILIYOR
            List<SelectListItem> Durumlistesi = new List<SelectListItem>();
            Durumlistesi.Add(new SelectListItem { Text = "Aktif", Value = "True" });
            Durumlistesi.Add(new SelectListItem { Text = "Pasif", Value = "False" });

            ViewBag.dgr1 = Durumlistesi;

            return View();
        }

        [HttpPost]
        public ActionResult MarkaEkle(Marka m) //DB KAYDETME ISLEMI
        {
            m.Durum = true;//AKTIF KAYIT
            c.Markas.Add(m);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MarkaSil(int id)//DB SILME ISLEMI
        {
            var markalar = c.Markas.Find(id);
            markalar.MarkaID = id;
            markalar.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MarkaGetir(int id) //DB KAYDETME ISLEMI
        {
            var markabul = c.Markas.Find(id);

            List<SelectListItem> Durumlistesi = new List<SelectListItem>();
            Durumlistesi.Add(new SelectListItem { Text = "Aktif", Value = "True" });
            Durumlistesi.Add(new SelectListItem { Text = "Pasif", Value = "False" });

            ViewBag.dgr1 = Durumlistesi;

            return View("MarkaGetir", markabul);
        }

        public ActionResult MarkaGuncelle(Marka m) //DB KAYDETME ISLEMI
        {
            var markagun = c.Markas.Find(m.MarkaID);
            markagun.MarkaAd = m.MarkaAd;
            markagun.Durum = m.Durum;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Marka/Index.cshtml
@using mvc_net_Crm.Models.Siniflar
@model List<Marka>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2><span style="color:red">.|Markalar  </span>.|Marka Listesi</h2>
<br />
<table id="tbl1" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Marka Adi</th>
            <th>Durum</th>
            <th style="width: 150px" align="center">#</th>
            <th style="width: 150px" align="center">#</th>
        </tr>
    </thead>
    @foreach (var k in Model)
    {
        <tr>
            <td>
                @k.MarkaID
            </td>
            <td>
                @k.MarkaAd
            </td>
            <td>
                @k.Durum
            </td>
            <td align="center">
                <a href="/Marka/MarkaGetir/@k.MarkaID" class="btn btn-success"><i class="fas fa-database"></i> Guncelle</a>
            </td>
            <td align="center">
                <a href="/Marka/MarkaSil/@k.MarkaID" class="btn btn-danger" align="right"><i class="fas fa-trash"></i> Sil</a>
            </td>
        </tr>
    }
</table>
<a href="/Marka/MarkaEkle" class="btn btn-primary">Marka Ekle</a>



@*DATATABLES YAPISI VE UI SEKILLENDIRME BLOGU*@

@*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
@*<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js "></script>*@
<link href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.dataTables.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.min.js"></script>

<script>
    $('#tbl1').dataTable({
       "language": {
            "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"
        }
    });
</script>

@*DATATABLES YAPISI VE UI SEKILLENDIRME BLOGU*@

Views/Marka/MarkaEkle.cshtml
@model mvc_net_Crm.Models.Siniflar.Marka
@{
    ViewBag.Title = "MarkaEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Marka Ekle</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.MarkaAd)
    @Html.TextBoxFor(x => x.MarkaAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Durum)
    @*Html.TextBoxFor(x => x.Durum, new { @class = "form-control" })*@
    @Html.DropDownListFor(x => x.Durum, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Kaydet</button>

</form>

Views/Marka/MarkaGetir.cshtml
@model mvc_net_Crm.Models.Siniflar.Marka
@{
    ViewBag.Title = "MarkaGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Marka Guncelleme</h2>
<br />
@using (Html.BeginForm("MarkaGuncelle", "Marka", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.MarkaID)
        @Html.LabelFor(x => x.MarkaAd)
        @Html.TextBoxFor(x => x.MarkaAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Durum)
        @*Html.TextBoxFor(x => x.Marka, new { @class = "form-control" })*@
        @Html.DropDownListFor(x => x.Durum, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        <br />
    </div>
    <button class="btn btn-warning">Guncelle</button>
}