Models/Siniflar/Parametre.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace mvc_net_Crm.Models.Siniflar
{
    public class Parametre
    {


        public Parametre() //DEFAULT BILGILER VERILIYOR
        {
            Durum = true;
        }


    [Key]
    public int ParametreID { get; set; }

    [Column(TypeName = "Varchar")]
    [StringLength(30)]
    public string ParametreTuru { get; set; }

    [Column(TypeName = "Varchar")]
    [StringLength(30)]
    public string ParametreAciklamasi { get; set; }
    public bool Durum { get; set; }

    }

}

Controllers/ParametreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls.Expressions;
using mvc_net_Crm.Models.Siniflar;

namespace mvc_net_Crm.Controllers
{
    public class ParametreController : Controller
    {
        // GET: Parametre
        Context c = new Context();
        public ActionResult Index()
        {
            //var kategoriler=c.Kategoris.ToList();
            var parametreler = c.Parametres.Where(x => x.Durum == true).ToList();//KOSULLU LISTELEME
            return View(parametreler);
        }

        [HttpGet]
        public ActionResult ParametreEkle() //BOS FORM SAYFASI CAGIRIYOR
        {

            return View();
        }

        [HttpPost]
        public ActionResult ParametreEkle(Parametre k) //DB KAYDETME ISLEMI
        {
            k.Durum = true;
            c.Parametres.Add(k);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ParametreSil(int id)//DB SILME ISLEMI
        {
            var param = c.Parametres.Find(id);
            param.ParametreID = id;
            param.Durum = false;
            //c.Kategoris.Remove(kate);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ParametreGetir(int id) //DB KAYDETME ISLEMI
        {
            var parametre = c.Parametres.Find(id);
            return View("ParametreGetir", parametre);
        }

        public ActionResult ParametreGuncelle(Parametre k) //DB KAYDETME ISLEMI
        {
            var param = c.Parametres.Find(k.ParametreID);
            param.ParametreTuru = k.ParametreTuru;
            param.ParametreAciklamasi = k.ParametreAciklamasi;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Parametre/Index.cshtml
@using mvc_net_Crm.Models.Siniflar;
@model List<Parametre>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2><span style="color:red">.|Parametreler </span>Tüm Parametreler Ekrani</h2>
<br />
<table id="tbl1" class="table table-striped table-bordered table-hover" style="width:100%">
    <thead>
        <tr>
            <!--<th>ID</th>-->
            <th>Parametre Turu</th>
            <th>Parametre Aciklamasi</th>
            <th>Parametre Durum</th>
            <th style="width: 150px" align="center">#</th>
            <th style="width: 150px" align="center">#</th>
        </tr>
    </thead>
    @foreach (var k in Model)
    {
        <tr>
            <!--<td>@k.ParametreID</td>-->
            <td>@k.ParametreTuru</td>
            <td>@k.ParametreAciklamasi</td>
            <td>@k.Durum</td>
            <td align="center">
                <a href="/Parametre/ParametreGetir/@k.ParametreID" class="btn btn-success"><i class="fas fa-database"></i> Guncelle</a>
            </td>
            <td align="center">
                <a href="/Parametre/ParametreSil/@k.ParametreID" class="btn btn-danger" align="right"><i class="fas fa-trash"></i> Sil</a>
            </td>
        </tr>
    }
</table>
<br />
<a href="/Parametre/ParametreEkle" class="btn btn-primary">Parametre Ekle</a>



@*DATATABLES YAPISI VE UI SEKILLENDIRME BLOGU*@

@*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
@*<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js "></script>*@
<link href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.dataTables.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.min.js"></script>

<script>
    $('#tbl1').dataTable({
        "language": {
            "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"
        }
    });
</script>

@*DATATABLES YAPISI VE UI SEKILLENDIRME BLOGU*@

Views/Parametre/ParametreEkle.cshtml
@model mvc_net_Crm.Models.Siniflar.Parametre
@{
    ViewBag.Title = "ParametreEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yeni Parametre Ekrani</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.ParametreTuru)
    @Html.TextBoxFor(x => x.ParametreTuru, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ParametreAciklamasi)
    @Html.TextBoxFor(x => x.ParametreAciklamasi, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Kaydet</button>

</form>

Views/Parametre/ParametreGetir.cshtml
@model mvc_net_Crm.Models.Siniflar.Parametre
@{
    ViewBag.Title = "ParametreGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Parametre Guncelleme</h2>
<br />
@using (Html.BeginForm("ParametreGuncelle", "Parametre", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.ParametreID)
        @Html.LabelFor(x => x.ParametreTuru)
        @Html.TextBoxFor(x => x.ParametreTuru, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.ParametreAciklamasi)
        @Html.TextBoxFor(x => x.ParametreAciklamasi, new { @class = "form-control" })
    <br />
    </div>
    <button class="btn btn-warning">Guncelle</button>
}