Models/Siniflar/TransactionTask.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace mvc_net_Crm.Models.Siniflar
{
    public class TransactionTask
    {

        public TransactionTask() //DEFAULT BILGILER VERILIYOR
        {
            Durum = true;
            OnayStatusu = "OnayBekliyor"; //Onaylandi //RedEdildi
            AcilisTarihi = DateTime.Now;
            SonIslemTarihi = DateTime.Now;
            Tutar = 0;

            //ToplamTutar = Adet * Fiyat;
        }


        [Key]
        public int TransactionTaskid { get; set; }


        public int Belgeid { get; set; }
        public DateTime AcilisTarihi { get; set; }
        public DateTime SonIslemTarihi { get; set; }


        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string CariBilgisi { get; set; } //TRANSACTIONA ISLEMDEN GELECEK

        public decimal Tutar { get; set; } //TRANSACTIONA ISLEMDEN GELECEK

        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string BelgeTuru { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string KayitAcanUser { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string KayitOnaylayanUser { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string OnayStatusu { get; set; }

        public bool Durum { get; set; }

    }
}

Controllers/TransactionTaskController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mvc_net_Crm.Models.Siniflar;
using static Google.Protobuf.Compiler.CodeGeneratorResponse.Types;

namespace mvc_net_Crm.Controllers
{
    public class TransactionTaskController : Controller
    {
        // GET: TransactionTask
        Context c = new Context(); //TRANSACTION DATASET
        Context d = new Context(); //FATURA-FATURAKALEM DATASET
        Context e = new Context(); //STOKHAREKET DATASET
        Context f = new Context(); //FINANSALHAREKET DATASET
        public ActionResult Index()
        {
            //var transaction = c.TransactionTasks.Where(x => x.Durum == true && x.OnayStatusu.Contains("Bekliyor")).ToList();
            var transaction = c.TransactionTasks.Where(x => x.Durum == true).ToList();
            return View(transaction);
        }


        [HttpPost]
        public ActionResult TransactionTaskEkle(TransactionTask k) //DB KAYDETME ISLEMI
        {
            //k.Durum = true;
            //c.Ambars.Add(k);
            //c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult TransactionTaskGetir(int id) //DB KAYDETME ISLEMI
        {
            var Transaction = c.TransactionTasks.Find(id);
            List<SelectListItem> onaycilar = (from x in c.Personels.Where(x => x.Durum == true).ToList()
                                                select new SelectListItem
                                                {
                                                    Text = x.PersonelAd + " " + x.PersonelSoyad,
                                                    Value = x.PersonelAd + " " + x.PersonelSoyad,
                                                }
                              ).ToList();
            ViewBag.dgr1 = onaycilar;

            List<SelectListItem> OnayParametrelistesi = new List<SelectListItem>();
            OnayParametrelistesi.Add(new SelectListItem { Text = "OnayBekliyor", Value = "OnayBekliyor" });
            OnayParametrelistesi.Add(new SelectListItem { Text = "Onaylandi", Value = "Onaylandi" });
            OnayParametrelistesi.Add(new SelectListItem { Text = "RedEdildi", Value = "RedEdildi" });

            ViewBag.dgr2 = OnayParametrelistesi;
            return View("TransactionTaskGetir", Transaction);
        }

        public ActionResult TransactionTaskGuncelle(TransactionTask k) //DB KAYDETME ISLEMI
        {
            var Transaction = c.TransactionTasks.Find(k.TransactionTaskid);
            int id  = c.TransactionTasks.Find(k.TransactionTaskid).Belgeid;
            var fatura = d.Faturalars.Find(id);
            var stokhareket=e.StokHarekets.Find(id);
            var finansalhareket = f.FinansalHarekets.Find(id);
            Transaction.OnayStatusu = k.OnayStatusu;
            Transaction.SonIslemTarihi = DateTime.Now;
            Transaction.KayitOnaylayanUser = k.KayitOnaylayanUser;
            if (Transaction.BelgeTuru.Contains("FATURA"))
            {
                fatura.OnayStatusu = k.OnayStatusu;
                e.FaturaKalems.AsEnumerable().Where(x => x.Faturaid == id).ToList().ForEach(x =>
                {
                    x.OnayStatusu = k.OnayStatusu;
                });
                c.SaveChanges();
                d.SaveChanges();
                e.SaveChanges();
            }

            if (Transaction.BelgeTuru.Contains("IRSALIYE"))
            {
                stokhareket.OnayStatusu = k.OnayStatusu;
                c.SaveChanges();
                e.SaveChanges();
            }

            if ((Transaction.BelgeTuru.Contains("ODEME")) || (Transaction.BelgeTuru.Contains("TAHSILAT")) || (Transaction.BelgeTuru.Contains("PARA_GONDERME")) )
            {
                finansalhareket.OnayStatusu = k.OnayStatusu;
                c.SaveChanges();
                f.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult TransactionTaskSil(int id)//DB SILME ISLEMI
        {
            var transaction = c.TransactionTasks.Find(id);
            transaction.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/TransactionTask/Index.cshtml
@using mvc_net_Crm.Models.Siniflar
@model List<TransactionTask>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2><span style="color:red">.|Transaction Loglari  </span> .|Tum Transaction Islem Onaylari</h2>
<br />

<table id="tbl1" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>BelgeID</th>
            <th>CariBilgisi</th>
            <th>BelgeTuru</th>
            <th>AcilisTarihi</th>
            <th>KayitAcan</th>
            <th>OnayVeren/Kaldiran</th>
            <th>Tutar</th>
            <th>KayitStatusu</th>
            <th>SonIslemTarihi</th>
            <th style="width: 150px">#</th>
            <th style="width: 150px">#</th>
        </tr>
    </thead>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.TransactionTaskid</td>
            <td>@k.Belgeid</td>
            <td>@k.CariBilgisi</td>
            <td>@k.BelgeTuru</td>
            <td>@k.AcilisTarihi</td>
            <td>@k.KayitAcanUser</td>
            <td>@k.KayitOnaylayanUser</td>
            <td>@k.Tutar</td>
            <td>@k.OnayStatusu</td>
            <td>@k.SonIslemTarihi</td>
            <td align="center">
                <a href="/TransactionTask/TransactionTaskGetir/@k.TransactionTaskid" class="btn btn-success"><i class="fas fa-database"></i> Guncelle</a>
            </td>
            <td align="center">
                <a href="/TransactionTask/TransactionTaskSil/@k.TransactionTaskid" class="btn btn-danger" align="right"><i class="fas fa-trash"></i> Sil</a>
            </td>
        </tr>
    }
</table>
@*<a href="/FinansalHareket/FinansalHareketEkle" class="btn btn-primary">Yeni Finansal Islem</a>*@


@*DATATABLES YAPISI VE UI SEKILLENDIRME BLOGU*@

@*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
@*<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js "></script>*@
<link href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.dataTables.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.min.js"></script>

<script>
    $('#tbl1').dataTable({
       "language": {
            "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"
        }
    });
</script>

@*DATATABLES YAPISI VE UI SEKILLENDIRME BLOGU*@

Views/TransactionTask/TransactionTaskGetir.cshtml
@model mvc_net_Crm.Models.Siniflar.TransactionTask
@{
    ViewBag.Title = "TransactionTaskGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Transaction Task Onay Islemleri</h2>
<br />
@using (Html.BeginForm("TransactionTaskGuncelle", "TransactionTask", FormMethod.Post))
{
    <div class="form-group">

        @Html.HiddenFor(x => x.TransactionTaskid)
        @Html.LabelFor(x => x.TransactionTaskid)
        @Html.TextBoxFor(x => x.TransactionTaskid, new { disabled = "disabled", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.BelgeTuru)
        @Html.TextBoxFor(x => x.BelgeTuru, new { disabled = "disabled", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Belgeid)
        @Html.TextBoxFor(x => x.Belgeid, new { disabled = "disabled", @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.KayitOnaylayanUser)
        @Html.DropDownListFor(x => x.KayitOnaylayanUser, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.OnayStatusu)
        @Html.DropDownListFor(x => x.OnayStatusu, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <button class="btn btn-warning">Guncelle</button>
}